apiVersion: v1
kind: Service
metadata:
  name: <service-name>
  labels:
    app: <app-name>
spec:
  type: NodePort
  selector:
    app: <app-name>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080