apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deployment-name>
spec:
  selector:
    matchLabels:
      app: <app-name>
  replicas: <no-of-replicas> !use 1
  template:
    metadata:
      labels:
        app: <app-name>
    spec:
      containers: 
        - name: <app-name>
          image: <username>/<repository>:<remote-image-name>
          ports:
            - containerPort: 80
  